apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-wildcard
  namespace: gitlab-system
spec:
  commonName: "*.fck8slab.local"
  dnsNames:
    - "*.fck8slab.local"
  secretName: gitlab-tls
  usages:
    - server auth
    - client auth
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fck8slab-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
