apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-wildcard
  namespace: gitlab-system
spec:
  commonName: "*.fck8slab.local"
  secretName: gitlab-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fck8slab-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
