apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: sso
  namespace: keycloak-system
spec:
  instances: 3
    #instances: 1
  hostname:
    hostname: keycloak.fck8slab.local
  http:
    tlsSecret: tls-keycloak-ingress
  ingress:
    className: nginx
    enabled: true
