apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-gpu-exporter
  namespace: kube-system  # 與 Service 同一個 namespace
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nvidia-gpu-exporter
      app.kubernetes.io/name: nvidia-gpu-exporter
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: http
      interval: 30s
      path: /metrics

