---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow.fck8slab.local.crt
  namespace: istio-system
spec:
  isCA: false
  commonName: kubeflow.fck8slab.local
  secretName: kubeflow.fck8slab.local.crt
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fck8slab-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow.fck8slab.local.crt
  namespace: kubeflow
spec:
  isCA: false
  commonName: kubeflow.fck8slab.local
  secretName: kubeflow.fck8slab.local.crt
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fck8slab-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
